(my-require-and-eval (ido nil idomenu)
                     (my-check-or-install-package 'ido-completing-read+)
                     (my-check-or-install-package 'ido-yes-or-no)
                     (ido-mode t)
                     (ido-everywhere t)
                     (ido-ubiquitous-mode t)
                     (ido-yes-or-no-mode t))

(my-require-and-eval (smex nil smex)
                     (smex-initialize)
                     (global-set-key (kbd "M-x") 'smex))
